services:
  mongodb:
    image: mongo:7
    container_name: posts-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_posts_data:/data/db

  redis:
    image: redis:7
    container_name: posts-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_posts_data:/data

volumes:
  mongodb_posts_data:
  redis_posts_data: